### PR TITLE
Support configuring parameters during notebook submission

### PR DESCRIPTION
**Pull request by ajbozarth**
Sister PR with lresende/enterprise_scheduler#6

Sub-Tasks:
- Implement Notebook parser
- Extend submission dialog
- Extend scheduler to set environment variables
- Integration tests on FfDL runtime

### CODE REVIEW

**Comment by ajbozarth** [comment]
Initial commit:

1. Parses for env vars that are accessed with `os.environ`
2. Creates an array of all unique env vars found
3. Currently logs the list to console for testing

Next Steps (either):
- surface the env vars to the user via the prompt
- clean up current code
  - move code to outside file
  - test and improve code performance

**Comment by ajbozarth** [comment]
Just committed a change which moves the new functions into a utils file and further separates the two functions functionality so the "sub-function" can be called directly in other potential use cases.

For now my next step will be adding the env vars to the form, I plan to test performance at a latter time.

**Comment by ajbozarth** [comment]
Just pushed the (finally) working code for surfacing the parsed env vars to the UI and taking in the user inputed values to send to the server. Based on my expected plans this should mean any further work will be in the server repo in a sister PR.

**Comment by ajbozarth** [comment]
pushed the remaining code written when creating the sister PR in the server repo. It includes making the cos bucket part of the form rather than hard-coded.

**Comment by ajbozarth** [comment]
Some remaining nits and todos:

- As mentioned on the server PR, I should probably split the bucket form entry into two, input bucket and output bucket
- I'd like to expand the env pattern to also include `os.environ.get()` (and maybe `%env`)

**Comment by ajbozarth** [comment]
I split the bucket as planed but am unsure if it's actually necessary, and if so if the naming conventions I used are best. @lresende opinions? (specifically on this)

**Comment by ajbozarth** [comment]
Updated/fixed the parsing, it now handles most edge cases and both key and get access to env vars.
The one edge case left "unaddressed" is detailed in the commit message.

**Comment by lresende** [comment]
Regarding the COS bucket changes, that was a good catch and didn't surfaced while we were using the shared env as the bucket was already available. Thanks.

As for the covered scenarios, I could not get default values to be recognized by the parsing:
```
user = os.getenv("USER", "Luciano Resende")
server = os.getenv('HOST', 'localhost')
```

Also, this is minor and I haven't actually made my mind yet. What would be better, flow the parameters by rows or by columns on the dialog box ?

image

**Pull request closed without merging**
